stages:
  - build
  - deploy

build_qa:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  stage: build
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - apk add --no-cache curl jq python3 py3-pip git
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker build --build-arg DEPLOY_BRANCH=develop --build-arg TIMESTAMP=$(date '+%Y%m%d%H%M%S') -f production/Dockerfile -t "$ECR_API_BASE_URL/qa/check/web:$CI_COMMIT_SHA"  .
    - docker push "$ECR_API_BASE_URL/qa/check/web:$CI_COMMIT_SHA"
  only:
    - develop

deploy_qa:
  image: python:3-alpine
  stage: deploy
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    CF_CACHE_TOKEN: $CF_CACHE_TOKEN
    CF_ZONE_ID: $CF_ZONE_ID
  script:
    - apk add --no-cache curl jq python3 py3-pip git
    - pip install botocore==1.17.47
    - pip install boto3==1.14.47
    - pip install ecs-deploy==1.11.0
    - ecs deploy ecs-qa  qa-check-web --image qa-check-web-c $ECR_API_BASE_URL/qa/check/web:$CI_COMMIT_SHA -r arn:aws:iam::848416313321:role/ECSSecretsAccessRole -s qa-check-web-c config /qa/check-web/config -s qa-check-web-c config_server /qa/check-web/config-server --timeout 3600
    - echo "new Image was deployed $ECR_API_BASE_URL/qa/check/web:$CI_COMMIT_SHA"
    - sh scripts/clear-cf-cache.sh
  only:
    - develop

build_live:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  stage: build
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - apk add --no-cache curl jq python3 py3-pip git
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker build --build-arg DEPLOY_BRANCH=master --build-arg TIMESTAMP=$(date '+%Y%m%d%H%M%S') -f production/Dockerfile -t "$ECR_API_BASE_URL/live/check/web:$CI_COMMIT_SHA"  .
    - docker push "$ECR_API_BASE_URL/live/check/web:$CI_COMMIT_SHA"
  only:
    - master

deploy_live:
  image: python:3-alpine
  stage: deploy
  when: manual
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    CF_CACHE_TOKEN: $CF_CACHE_TOKEN
    CF_ZONE_ID: $CF_ZONE_ID
  script:
    - apk add --no-cache curl jq python3 py3-pip git
    - pip install botocore==1.17.47
    - pip install boto3==1.14.47
    - pip install ecs-deploy==1.11.0
    - ecs deploy ecs-live  live-check-web --image live-check-web-c $ECR_API_BASE_URL/live/check/web:$CI_COMMIT_SHA -r arn:aws:iam::848416313321:role/ECSSecretsAccessRole -s live-check-web-c config /live/check-web/config -s live-check-web-c config_server /live/check-web/config-server --timeout 3600
    - echo "new Image was deployed $ECR_API_BASE_URL/live/check/web:$CI_COMMIT_SHA"
    - sh scripts/clear-cf-cache.sh
  only:
    - master
